include config.mk

################################################################################
# General build tools and flags
################################################################################

CC := gcc
OBJCOPY := objcopy
OBJDUMP := objdump
CFLAGS := -Wall -pedantic -MMD -MP -g
CFLAGS += -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums

################################################################################
# Kilombo Section
################################################################################

ifeq ($(KILOMBO),y)
CPPFLAGS += -I$(KILOMBO_PATH)/include
CFLAGS += -O0
LDLIBS += -L$(KILOMBO_PATH)/lib -lsim -lSDL -lm -ljansson
libs :=
endif

################################################################################
# AVR Target Section
################################################################################

ifneq ($(KILOMBO),y)
CC := avr-$(CC)
OBJCOPY := avr-$(OBJCOPY)
OBJDUMP := avr-$(OBJDUMP)
CPPFLAGS += -DF_CPU=8000000 -I$(KILOLIB_PATH)
CFLAGS += -O3 -mmcu=atmega328p
libs += $(KILOLIB_PATH)/build/kilolib.a
flash += -R .eeprom -R .fuse -R .lock -R .signature
eeprom += -j .eeprom --set-section-flags=.eeprom="alloc,load" --change-section-lma .eeprom=0
endif

################################################################################
# Application configuration
################################################################################

ifeq ($(SKIP_ELECTION),y)
CFLAGS += -DSKIP_ELECTION
endif

ifeq ($(KILOMBO),y)
CFLAGS += -DKILOMBO
endif

ifeq ($(VISUAL_TPL),y)
CFLAGS += -DVISUAL_TPL
endif

ifeq ($(VISUAL_APP),y)
CFLAGS += -DVISUAL_APP
endif

ifeq ($(VERBOSE_TPL),y)
CFLAGS += -DVERBOSE_TPL
endif

ifeq ($(VERBOSE_APP),y)
CFLAGS += -DVERBOSE_APP
endif

ifeq ($(VERBOSE_BUF),y)
CFLAGS += -DVERBOSE_BUF
endif

################################################################################
# Build targets
################################################################################

.PHONY: clean all

objects := app.o buf.o tpl.o dis.o spt.o hnt.o
depends = $(patsubst %.o,%.d,$(objects))

executable := wsc

all: $(executable)

clean:
	@$(RM) $(executable) $(objects) $(depends) *.hex *.elf *.bin *.eep *.lss

$(executable): $(objects) $(libs)
	$(CC) $(CFLAGS) $(LDLIBS) -o $@ $^

$(objects): config.mk Makefile

hex: $(executable)
	$(OBJCOPY) -O ihex $(flash) $< $(executable).hex

eep: $(executable)
	$(OBJCOPY) -O ihex $(eeprom) $< $(executable).eep

bin: $(executable)
	$(OBJCOPY) -O binary $(flash) $< $(executable).bin

lss: $(executable)
	$(OBJDUMP) -d -S $< > $(executable).lss

# Include dependency files autogenerated rules
ifneq ($(MAKECMDGOALS),clean)
-include $(depends)
endif

