include config.mk

CC := gcc

CPPFLAGS := -I$(KILO_PATH)/include
CFLAGS := -g -O0 -Wall -pedantic -MMD -MP
LDLIBS := -L$(KILO_PATH)/lib -lsim -lSDL -lm -ljansson

ifeq ($(SKIP_ELECTION),y)
CFLAGS += -DSKIP_ELECTION
endif

ifeq ($(KILOMBO),y)
CFLAGS += -DKILOMBO
endif

ifeq ($(VISUAL_TPL),y)
CFLAGS += -DVISUAL_TPL
endif

ifeq ($(VISUAL_APP),y)
CFLAGS += -DVISUAL_APP
endif

ifeq ($(VERBOSE_TPL),y)
CFLAGS += -DVERBOSE_TPL
endif

ifeq ($(VERBOSE_APP),y)
CFLAGS += -DVERBOSE_APP
endif


.PHONY: clean all

objects := app.o buf.o tpl.o discover.o spt.o wsc.o
depends = $(patsubst %.o,%.d,$(objects))

target := wsc

all: $(target)

clean:
	$(RM) $(target) $(objects) $(depends)

$(target): $(objects)
	$(CC) $(CFLAGS) $(LDLIBS) -o $@ $^

$(objects): config.mk Makefile

# Include dependency files autogenerated rules
ifneq ($(MAKECMDGOALS),clean)
-include $(depends)
endif

